export const ta = [
  {
    name: "Raj Maitra",
    desc: "Pen-and-paper engineer turned keyboard warrior in multiple rabbit holes. Often known for making a mess. An actual rabbit.",
    image: "raj",
    bgColor: "bg-black",
    textColor: "text-white",
    headingColor: "text-orange",
    twitter: "https://twitter.com/RajarshiMaitra",
    github: "https://github.com/rajarshimaitra",
  },

  // {
  //   name: "Stratospher",
  //   desc:
  //     "Witchcrafting the gossip between Bitcoin nodes. But Pieter Wuille doesn't know its her cat who writes all the code.",
  //   image: "stratospher",
  //   bgColor: "bg-orange",
  //   textColor: "text-black",
  //   headingColor: "text-black",
  //   twitter: "https://twitter.com/spherostrat",
  //   github: "https://github.com/stratospher",
  // },
  {
    name: "Saurabh S",
    desc: "PM juggling Bitcoin FOSS projects and ventures like a circus performer.",
    image: "sourav",
    bgColor: "bg-black",
    textColor: "text-white",
    headingColor: "text-orange",
    twitter: "https://twitter.com/SetuSaurabh",
    github: "https://github.com/setusaurabh",
  },

  {
    name: "Anmol Sharma",
    desc: "When he is not talking about Bitcoin,he is busy writing code. But let's be honest, he is usually busy talking about Bitcoin.",
    image: "anmol",
    bgColor: "bg-orange",
    textColor: "text-black",
    headingColor: "text-black",
    twitter: "https://twitter.com/theanmolsharma_",
    github: "https://github.com/theanmolsharma",
  },
  {
    name: "Emjshrx",
    desc: "Joined Bitshala to run Bitcoin Core on his Dive Computer. Didn’t work, but he’ll keep trying.",
    image: "emil",
    bgColor: "bg-orange",
    textColor: "text-black",
    headingColor: "text-black",
    twitter: "https://twitter.com/emjshrx",
    github: "https://github.com/emjshrx",
  },
];

export const ta2 = [
  {
    name: "RAJ",
    desc: "Lead, Bitshala",
    image: "raj",
    bgColor: "bg-black",
    textColor: "text-white",
    headingColor: "text-orange",
    twitter: "https://twitter.com/RajarshiMaitra",
    github: "https://github.com/rajarshimaitra",
  },
  {
    name: "ANMOL SHARMA",
    desc: "Engineer, Bold",
    image: "anmol",
    bgColor: "bg-black",
    textColor: "text-white",
    headingColor: "text-orange",
    twitter: "https://twitter.com/theanmolsharma_",
    github: "https://github.com/theanmolsharma",
  },
  {
    name: "CODINGP110",
    desc: "Developer, BDK",
    image: "codingp110",
    bgColor: "bg-green",
    textColor: "text-white",
    headingColor: "text-yellow",
    github: "https://github.com/110CodingP",
  },
  {
    name: "BTC NOOB",
    desc: "Bitcoin Educator",
    image: "btcnoob",
    bgColor: "bg-blue",
    textColor: "text-white",
    headingColor: "text-orange",
    github: "https://github.com/BTCNoob21m",
  },
  {
    name: "DHRUVIL",
    desc: "Developer, Lampo",
    image: "dhruvil",
    bgColor: "bg-purple",
    textColor: "text-white",
    headingColor: "text-yellow",
    github: "https://github.com/dhruvil1514",
  },
  {
    name: "CHAITIKA",
    desc: "Developer, Silent Payments",
    image: "chaitika",
    bgColor: "bg-green",
    textColor: "text-white",
    headingColor: "text-black",
    github: "https://github.com/chaitika",
  },
  // {
  //   name: "BEULAH",
  //   desc: "Protocol Developer",
  //   image: "beulah",
  //   bgColor: "bg-blue",
  //   textColor: "text-white",
  //   headingColor: "text-orange",
  // },
  {
    name: "BALA",
    desc: "Protocol Developer",
    image: "bala",
    bgColor: "bg-black",
    textColor: "text-white",
    headingColor: "text-green",
  },
];

export const team = [
  {
    name: "Raj Maitra",
    desc: "Pen-and-paper engineer turned keyboard warrior in multiple rabbit holes. Often known for making a mess. An actual rabbit.",
    image: "raj",
    bgColor: "bg-black",
    textColor: "text-white",
    headingColor: "text-orange",
    twitter: "https://twitter.com/RajarshiMaitra",
    github: "https://github.com/rajarshimaitra",
  },
  {
    name: "Saurabh S",
    desc: "PM juggling Bitcoin FOSS projects and ventures like a circus performer.",
    image: "sourav",
    bgColor: "bg-orange",
    textColor: "text-black",
    headingColor: "text-black",
    twitter: "https://twitter.com/SetuSaurabh",
    github: "https://github.com/setusaurabh",
  },
  {
    name: "Anmol Sharma",
    desc: "When he is not talking about Bitcoin,he is busy writing code. But let's be honest, he is usually busy talking about Bitcoin.",
    image: "anmol",
    bgColor: "bg-orange",
    textColor: "text-black",
    headingColor: "text-black",
    twitter: "https://twitter.com/theanmolsharma_",
    github: "https://github.com/theanmolsharma",
  },
  {
    name: "Jatin",
    desc: "Exploring the depths of Bitcoin and cryptography, always eager to learn and share knowledge.",
    image: "anmol",
    bgColor: "bg-black",
    textColor: "text-white",
    headingColor: "text-orange",
    twitter: "https://twitter.com/jatinbtc",
    github: "https://github.com/jatinbtc",
  },
  {
    name: "Veronika",
    desc: "Passionate about open source and building communities around Bitcoin development.",
    image: "anmol",
    bgColor: "bg-black",
    textColor: "text-white",
    headingColor: "text-orange",
    twitter: "https://twitter.com/veronikabtc",
    github: "https://github.com/veronikabtc",
  },
  {
    name: "Vyras",
    desc: "Always experimenting with new ideas in Bitcoin and Lightning, bringing fresh perspectives to the team.",
    image: "anmol",
    bgColor: "bg-orange",
    textColor: "text-black",
    headingColor: "text-black",
    twitter: "https://twitter.com/vyrasbtc",
    github: "https://github.com/vyrasbtc",
  },
  {
    name: "Paperpsych",
    desc: "If he’s not designing, he’s writing copy, if he’s not doing that, he’s planning some events. If not that.. he’s probably watching Mad Men!",
    image: "paperpsych",
    bgColor: "bg-orange",
    textColor: "text-black",
    headingColor: "text-black",
    twitter: "https://twitter.com/_paperpsych",
    github: "https://github.com/paperpsych",
  },
  {
    name: "Keraliss",
    desc: "Contemplating by a river in his humble hut with his laptop, he codes. He says thats all he needs.",
    image: "keraliss",
    bgColor: "bg-black",
    textColor: "text-white",
    headingColor: "text-orange",
    twitter: "https://twitter.com/keraliss1",
    github: "https://github.com/keraliss",
  },
];

export const advisors = [
  {
    name: "Adam Jonas",
    desc: "An invisible force in Bitcoin. Nobody knows what he does. So we’ve stopped asking.",
    image: "adam",
    bgColor: "bg-orange",
    textColor: "text-black",
    headingColor: "text-black",
    twitter: "https://twitter.com/adamcjonas",
  },
  {
    name: "Adi Shankar",
    desc: "The monk who gave us the name and the logo, but never explained what they mean.",
    image: "adi",
    bgColor: "bg-black",
    textColor: "text-white",
    headingColor: "text-orange",
    twitter: "https://twitter.com/adi_shankara_",
  },
];

export const reviewClubTa = [
  {
    name: "Raj Maitra",
    desc: "Pen-and-paper engineer turned keyboard warrior in multiple rabbit holes. Often known for making a mess. An actual rabbit.",
    image: "raj",
    bgColor: "bg-black",
    textColor: "text-white",
    headingColor: "text-orange",
    twitter: "https://twitter.com/RajarshiMaitra",
    github: "https://github.com/rajarshimaitra",
  },

  // {
  //   name: "Stratospher",
  //   desc:
  //     "Witchcrafting the gossip between Bitcoin nodes. But Pieter Wuille doesn't know its her cat who writes all the code.",
  //   image: "stratospher",
  //   bgColor: "bg-orange",
  //   textColor: "text-black",
  //   headingColor: "text-black",
  //   twitter: "https://twitter.com/spherostrat",
  //   github: "https://github.com/stratospher",
  // },
];

export const testimonial = [
  [
    {
      text: "Personally, I was able to familiarize myself more deeply with concepts I only knew at a surface level. I was also able to get myself up-to-date with many recent developments. And, a special shoutout goes to the other weekly clubs conducted by Bitshala that I attended alongside the cohort — Bitcoin Optech Club, Reading Club, and the PR Review Club. They covered a ton of additional information, and attending them is a must for anyone who wants to stay up-to-date with everything happening in Bitcoin.  I can assure you that anyone who is able to stick through the entire Mastering Bitcoin cohort will gain a better understanding of Bitcoin than 99% of people and will be in a good position to grab opportunities in the Bitcoin space or start something of their own. ",
      name: "Rishabh",
      cohort: "on Mastering Bitcoin",
      img: "/testimonial/rishabh.png",
    },
    {
      text: "Anyone spending four hours of their evenings, in a week, can gain valuable knowledge and experience about technical, economic and philosophical landscape of Bitcoin. The community makes learning fun and effective for me.",
      name: "Bala",
      cohort: "on PB Cohort",
      img: "/testimonial/bala.png",
    },
  ],
  [
    {
      text: "The questions and practical exercises. I think they are very well designed to make you deeply reflect on the studied topic. It help me a lot to consolidate knowledge. The kindle and super fast support from bitshala team and the rest of bitshala comunity. Sharing knowledge, experience and a lot of good stuff. I was awesome to me you all. I loved the day when instead of following the planned agenda and discussing the weekly questions, there was a debate on philosophical and profound topics about money and bitcoin. It was great!",
      name: "Lazysatoshi",
      cohort: "on Study Cohorts",
      img: "/testimonial/lazy.webp",
    },
    {
      text: "Participating in the Programming Bitcoin cohort was one of the most transformative experience for me. The sessions provided invaluable clarity on key concepts such as public key cryptography, giving me a crystal-clear understanding. It was a pivotal moment in my Bitcoin journey that boosted my confidence in mastering Bitcoin's technical aspects.",
      name: "Claddy",
      cohort: "on BPD & Bitshala Community",
      img: "/testimonial/claddy.png",
    },
    {
      text: "If you’re a bitcoin user, you'd like to have a front row 'chair' over all things bitcoin. Bitshala fixes this!",
      name: "MangoElephant",
      cohort: "on Club Activities",
      img: "/testimonial/mango.png",
    },
  ],
  [
    {
      text: "I came across Bitshala while working on an SOB assignment and decided to join their Bitcoin Protocol Development cohort. Honestly, it’s been such an amazing experience! In just 8 weeks, I learned so much, thanks to their awesome community and support. Shoutout to Raj for getting me started with the SP project and a huge thanks to Anmol for always helping me out without making me feel silly! Tanveer on BPD and Bitshala Community",
      name: "Tanveer",
      cohort: "on BPD and Bitshala Community",
      img: "/testimonial/tanveer.png",
    },
    {
      text: "Before the cohort I was just a person with some idea of Bitcoin transactions, mining etc. 'Cool technology', I thought. I had no idea of what the code looks like, who are the people working behind this. After the cohort I had a whole new understanding of how Bitcoin works and the people who make it Bitcoin.",
      name: "CodingP110",
      cohort: "on Bitcoin Protocol Dev Cohort",
      img: "/testimonial/codingp110.png",
    },
  ],
];
